SITE_BASE_URL = "https://pypi.org/"
SEARCH_PATH = "search/?q="
LOGIN_PAGE_PATH = "account/login/"
DEFAULT_PROJECT_NAME = "selenium"
DEFAULT_PASSWORD = "!@#$%^&*()12Qw"
MAX_COUNT_PROJECTS_IN_SEARCH_RESULT = 20
# SEARCH_ORDER_BY_DEFAULT = "&o="
